name: Reusable Node CI

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

jobs:
  ci:
    name: Install • Lint • Test
    runs-on: ubuntu-latest

    steps:
      # Explain what each step does (maintainability!)
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'npm' # speeds up installs

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint --if-present

      - name: Test
        run: npm test
