name: Secret Workflow

on:
  push:
    branches: [ main ]

jobs:
  secret-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Secret Safely
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        run: |
          echo "✅ Secret is available!"
          echo "Secret length is: $(echo $ACCESS_TOKEN | wc -c)"
